config/routes.rb
Rails.application.routes.draw do
  root "mesa#index"
  get "join",to: "mesa#join"
  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :post
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/platform.rb
class Platform < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mesa_controller.rb
class MesaController < ApplicationController
    def index
    end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mesa_helper.rb
module MesaHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navber.html.erb
<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mt-0 mb-0 mesa-nav ">
            <button class="navbar-toggler" 
                    type="button" 
                    data-toggle="collapse" 
                    data-target="#navbarNav4" 
                    aria-controls="navbarNav4" 
                    aria-expanded="false" 
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <a class="navbar-brand" href="/">
                    <img src="/assets/logo.png" class="icon">
                </a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <%= link_to "入隊方法",join_path,class:"nav-link"%>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="kiyaku.html">クラン規約</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="timer.html">ギャラリー</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">メンバー用</a>
                    </li>
                </ul>
            </div>
        </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MESA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <% #stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>
<style>
  body{
    background: linear-gradient( 0deg, rgba(246, 255, 255, 1), rgba(255,255,255,0.6), rgba(255,255,255,0.2), rgba(255,255,255,0)),
    url(/assets/back01.png)fixed;
    background-repeat: no-repeat;
    background-size:cover;
    max-width:2000px;
    height:100%;
      }
  .logo-box{text-align: center;
            margin-top:80px;
            margin-bottom:80px;
  }
  .logo{ width: 15%;
  }
  .L-bar{background-color:#0000000;
          height:800px;
          margin-left:30%;

          }
  .R-bar{background-color:#0000000;
          height:800px;
          margin-right:15%;

          }
  .center-box{background-color:#292f33;

              margin-right:8%;
              margin-left:8%;
              height:100%;
          
  }
  .footer{height:120px;
          background-color:gray;
  }
  .mesa-nav{height:100px;}
  .icon{height:50px;}
  .mesa-slide{margin-left:50px;margin-right:50px;padding-top:20px;}
</style>
  <body>
    
  <header>
    <%= render"layouts/navber" %>
  </header>
  
    <div class="logo-box">
      <img src="/assets/emblem2.png" class="logo">
    </div>
    
    <div class="container-fluid background">
        <div class="row">
    
            
            <div class="col-sm-9">
              <%= yield %>
            </div>
          
            <div class="col-sm-3 R">
              <div class="R-bar">
                <a class="twitter-timeline" data-theme="dark" href="https://twitter.com/Maitake_Ninja?ref_src=twsrc%5Etfw" height=100%>
                  Tweets by Maitake_Ninja
                </a> 
              <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
              </div>
            </div>
            
        </div>
    </div>
    <footer class="footer">
      
    </footer>
  </body>
</html>

app/views/mesa/index.html.erb
<div class="center-box">
    <h1>クラン概要</h1>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.image %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>